using MatchSync.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MatchSync.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class BookingController : ControllerBase
    {
        // ADD THIS: This is the bridge to your SQL Database
        private readonly MatchSyncContext _context;

        // ADD THIS: This "Constructor" initializes the connection
        public BookingController(MatchSyncContext context)
        {
            _context = context;
        }

        [HttpGet("calculate-volleyball")]
        public IActionResult GetVolleyballRate(DateTime startTime)
        {
            decimal rate;
            if (startTime.Hour >= 8 && startTime.Hour < 14)
            {
                rate = 500.00m;
            }
            else
            {
                rate = 650.00m;
            }

            return Ok(new { Rate = rate, Currency = "PHP" });
        }

        [HttpPost("reserve")]
        public async Task<IActionResult> CreateBooking(Booking newBooking)
        {
            if (newBooking.BookingDate < DateTime.Today)
            {
                return BadRequest("You cannot book a date in the past.");
            }

            newBooking.BookingStatus = "Pending";
            newBooking.CreatedAt = DateTime.Now;

            // Now _context will work because we initialized it above
            _context.Bookings.Add(newBooking);
            await _context.SaveChangesAsync();

            return Ok(new
            {
                // Note: ReferenceCode is generated by SQL, so it might be null 
                // until you reload the object or use a fresh query.
                Message = "Reservation saved!",
                Reference = newBooking.ReferenceCode,
                Status = newBooking.BookingStatus
            });
        }
        [HttpPost("cancel/{id}")]
        public async Task<IActionResult> CancelBooking(int id)
        {
            // 1. Find the booking in your SQL table
            var booking = await _context.Bookings.FindAsync(id);

            if (booking == null)
            {
                return NotFound("Booking not found.");
            }

            // 2. Logic Check: Calculate the time difference
            // Combine BookingDate and StartTime for a full timestamp
            DateTime bookingDateTime = booking.BookingDate.Add(booking.StartTime);
            TimeSpan timeUntilBooking = bookingDateTime - DateTime.Now;

            // 3. Rule: Must be more than 24 hours before the session
            if (timeUntilBooking.TotalHours < 24)
            {
                return BadRequest("Cancellations must be made at least 24 hours in advance for a refund.");
            }

            // 4. Update Status instead of deleting (for Data Integrity)
            booking.BookingStatus = "Cancelled";
            await _context.SaveChangesAsync();

            return Ok(new { Message = "Booking cancelled successfully. Refund processing." });
        }
        [HttpGet("user-stats/{userId}")]
        public async Task<IActionResult> GetUserStats(int userId)
        {
            // 1. Find all completed bookings for this user
            var completedSessions = await _context.Bookings
                .Where(b => b.UserID == userId && b.BookingStatus == "Completed")
                .ToListAsync();

            // 2. Count sessions that lasted 2 hours or more
            int qualifyingSessions = 0;
            foreach (var session in completedSessions)
            {
                var duration = session.EndTime - session.StartTime;
                if (duration.TotalHours >= 2)
                {
                    qualifyingSessions++;
                }
            }

            // 3. Determine if they hit the 5-booking hurdle
            bool isProvenUser = qualifyingSessions >= 5;

            return Ok(new
            {
                TotalQualifyingSessions = qualifyingSessions,
                IsProven = isProvenUser,
                Message = isProvenUser ? "Status: Proven User" : $"Need {5 - qualifyingSessions} more 2-hour sessions."
            });
        }
        [HttpPost("confirm-payment/{bookingId}")]
        public async Task<IActionResult> ConfirmPayment(int bookingId, decimal amountPaid)
        {
            var booking = await _context.Bookings.FindAsync(bookingId);

            if (booking == null) return NotFound("Booking not found.");

            // Logic: In a real app, you would verify the amount is exactly 50% here
            // For your capstone, we update the status to 'Confirmed'
            booking.BookingStatus = "Confirmed";

            await _context.SaveChangesAsync();

            return Ok(new
            {
                Message = "Downpayment Received!",
                NewStatus = booking.BookingStatus,
                Reference = booking.ReferenceCode
            });
        }
    }
}